### ISSUE TITLE
Bug: Setting Up In MacOS

### ISSUE THREAD

**Issue by ahmetutku** [MLDSAI/puterbot#29]
Hello,
I was trying to set up everything in MacOS. I removed "pywin32==306" from the requirements.txt file instead of the readme file since it is not compatible with my Mac. However, I have been getting errors (as seen in the images attached).
<img width="1440" alt="Screen Shot 2023-04-21 at 19 25 05" src="https://user-images.githubusercontent.com/82727731/233760368-c1ceba08-8243-4bc0-8ccf-e0def99337c6.png">
<img width="1440" alt="Screen Shot 2023-04-21 at 19 25 22" src="https://user-images.githubusercontent.com/82727731/233760369-a41487ba-083f-44a8-84c2-102fd7eee898.png">

**Comment by 0dm** [comment]
Hi @ahmetutku,

I also had to remove the pywin32 requirement on MacOS. I recommend removing your files and trying again, with these exact steps (from the README):

```
 git clone https://github.com/MLDSAI/puterbot.git
 cd puterbot
 python3.10 -m venv .venv
 source .venv/bin/activate
 pip install wheel
 ```
 `nano requirements.txt` // (or use vim lol)
 remove the line "pywin32==306"
 ctrl+x => y
 
 ```
 pip install -r requirements.txt
 pip install -e .
 alembic upgrade head
 ```
 check if it works via `python3.10 -m pytest`
if so, you should be fine to run `python puterbot/record.py "test"`

I also suggest doing a very brief recording, just click around a few times and type a word.

**Comment by abrichr** [comment]
Thank you @ahmetutku and @0dm ! 

> I also had to remove the pywin32 requirement on MacOS. I

Fixed in https://github.com/MLDSAI/puterbot/pull/31

> Longer recordings tend to cause more issues on my end.

Thank you for flagging, there is an open issue here: https://github.com/MLDSAI/puterbot/issues/5

> However, I have been getting errors (as seen in the images attached).

@ahmetutku in the future please copy and paste instead of taking a screenshot of text. It appears you are using the standard `pynput` from https://github.com/moses-palmer/pynput and not our custom version from https://github.com/abrichr/pynput. The latter is specified in the requirements.txt. Please stash your changes with `git stash`, try again, and let us know if this fixes your issue! 🙏

**Comment by abrichr** [comment]
@ahmetutku can we close this?
